2023-11-11 08:44:06,033.33 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unmatched ']' (<stdin>, line 1)
NoneType: None
2023-11-11 08:44:14,257.257 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - name 'data' is not defined
NoneType: None
2023-11-11 08:46:16,162.162 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - [Errno 2] No such file or directory: 'path_to_file/person.json'
NoneType: None
2023-11-11 08:46:36,674.674 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - [Errno 2] No such file or directory: 'path_to_file/person.json'
NoneType: None
2023-11-11 08:47:31,731.731 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - 0
NoneType: None
2023-11-11 08:47:37,157.157 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unhashable type: 'list'
NoneType: None
2023-11-11 08:48:13,379.379 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - invalid syntax (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,103.103 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - name 'fname' is not defined
NoneType: None
2023-11-11 08:50:01,104.104 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,104.104 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,117.117 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,117.117 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,118.118 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,119.119 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,119.119 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,120.120 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:01,124.124 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:06,212.212 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,498.498 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - name 'fname' is not defined
NoneType: None
2023-11-11 08:50:24,499.499 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,500.500 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,501.501 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,502.502 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,503.503 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,504.504 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,504.504 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,505.505 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:50:24,505.505 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - unexpected indent (<stdin>, line 1)
NoneType: None
2023-11-11 08:51:29,988.988 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - expected an indented block (<stdin>, line 2)
NoneType: None
2023-11-11 08:51:32,724.724 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - EOL while scanning string literal (<stdin>, line 1)
NoneType: None
2023-11-11 09:17:10,608.608 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - invalid syntax (<stdin>, line 1)
NoneType: None
2023-11-11 09:17:18,464.464 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - invalid syntax (<stdin>, line 1)
NoneType: None
2023-11-11 09:17:26,496.496 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - name 'library' is not defined
NoneType: None
2023-11-11 11:02:12,654.654 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - 'MetaData'
NoneType: None
2023-11-11 15:53:17,255.255 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - name 'ref_df' is not defined
NoneType: None
2023-11-11 16:07:06,487.487 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - 
NoneType: None
2023-11-11 16:32:47,576.576 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - 
NoneType: None
2023-11-12 08:21:11,508.508 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - name 'python' is not defined
NoneType: None
2023-11-12 08:21:35,640.640 /projects/b1139/environments/pytorch-1.11-emodpy-py39/lib/python3.9/site-packages/idmtools/core/exceptions.py:90 idmtools_error_handler [ERROR] (31603,140018376099648) - EOL while scanning string literal (<stdin>, line 1)
NoneType: None
